apiVersion: v1
kind: Service
metadata:
  namespace: dagligvare
  name: backend-service
spec:
    selector:
        app: backend-springboot
    ports:
        - port: 8080
          targetPort: 8080
    type: ClusterIP
